### ISSUE TITLE
staking-miner-playground: `N=22500, C=1500, V=300` doesn't work

### ISSUE THREAD

**Issue by niklasad1** [paritytech/polkadot-staking-miner#774]
```bash
➜  staking-miner-playground git:(na-chore-staking-miner-playground-update-deps) ✗ ./target/release/staking-miner-playground --dev
nominators 22500 / validators 300 / candidates 1500 / maxNomination 16.
2024-01-18 16:15:40 Substrate Node
2024-01-18 16:15:40 ✌️  version 4.0.0-dev-f0f48117e5e
2024-01-18 16:15:40 ❤️  by Substrate DevHub <https://github.com/substrate-developer-hub>, 2017-2024
2024-01-18 16:15:40 📋 Chain specification: Development
2024-01-18 16:15:40 🏷  Node name: daily-trucks-6182
2024-01-18 16:15:40 👤 Role: AUTHORITY
2024-01-18 16:15:40 💾 Database: RocksDb at /tmp/substrateDbVsbm/chains/dev/db/full
2024-01-18 16:15:44 [0] 💸 generated 22500 npos voters, 1500 from validators and 21000 nominators
2024-01-18 16:15:44 [0] 💸 generated 1500 npos targets

====================

Version: 4.0.0-dev-f0f48117e5e

   0: sp_panic_handler::panic_hook
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sp-panic-handler-12.0.0/src/lib.rs:166:18
      sp_panic_handler::set::{{closure}}
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sp-panic-handler-12.0.0/src/lib.rs:62:12
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2021:9
      std::panicking::rust_panic_with_hook
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:783:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
   4: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   5: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   6: core::result::unwrap_failed
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
   7: core::result::Result<T,E>::expect
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1034:23
      <&mut dyn sp_wasm_interface::FunctionContext as sp_io::allocator::Allocator>::malloc_version_1
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sp-io-29.0.0/src/lib.rs:1555:3
      sp_io::allocator::malloc_version_1::{{closure}}
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sp-io-29.0.0/src/lib.rs:1551:1
      tracing::span::Span::in_scope
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/span.rs:1102:9
   8: sp_io::allocator::malloc_version_1
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sp-io-29.0.0/src/lib.rs:1551:1
      sp_io::allocator::ExtAllocatorMallocVersion1::call
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sp-io-29.0.0/src/lib.rs:1551:1
   9: <sp_io::allocator::HostFunctions as sp_wasm_interface::HostFunctions>::register_static::{{closure}}::{{closure}}::{{closure}}
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sp-io-29.0.0/src/lib.rs:1551:1
      core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panic/unwind_safe.rs:272:9
      std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
      <sp_io::allocator::HostFunctions as sp_wasm_interface::HostFunctions>::register_static::{{closure}}::{{closure}}
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sp-io-29.0.0/src/lib.rs:1551:1
      <sc_executor_wasmtime::imports::Registry as sp_wasm_interface::HostFunctionRegistry>::with_function_context
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-executor-wasmtime-0.28.0/src/imports.rs:104:3
  10: <sp_io::allocator::HostFunctions as sp_wasm_interface::HostFunctions>::register_static::{{closure}}
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sp-io-29.0.0/src/lib.rs:1551:1
      <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1),R>>::into_func::wasm_to_host_shim::{{closure}}::{{closure}}
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-8.0.1/src/func.rs:1916:41
      core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panic/unwind_safe.rs:272:9
      std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  11: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
      <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1),R>>::into_func::wasm_to_host_shim::{{closure}}
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-8.0.1/src/func.rs:1911:29
      wasmtime::func::Caller<T>::with
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-8.0.1/src/func.rs:1714:9
      <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1),R>>::into_func::wasm_to_host_shim
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-8.0.1/src/func.rs:1900:34
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <(A1,A2) as wasmtime::func::typed::WasmParams>::invoke::{{closure}}
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-8.0.1/src/func/typed.rs:592:21
      <(A1,) as wasmtime::func::HostAbi>::call
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-8.0.1/src/func.rs:1620:18
      <(A1,A2) as wasmtime::func::typed::WasmParams>::invoke
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-8.0.1/src/func/typed.rs:590:17
      wasmtime::func::typed::TypedFunc<Params,Results>::call_raw::{{closure}}
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-8.0.1/src/func/typed.rs:180:26
      wasmtime_runtime::traphandlers::catch_traps::call_closure
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-runtime-8.0.1/src/traphandlers.rs:243:18
  29: wasmtime_setjmp
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-runtime-8.0.1/src/helpers.c:55:3
  30: wasmtime_runtime::traphandlers::catch_traps::{{closure}}
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-runtime-8.0.1/src/traphandlers.rs:225:9
      wasmtime_runtime::traphandlers::<impl wasmtime_runtime::traphandlers::call_thread_state::CallThreadState>::with::{{closure}}
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-runtime-8.0.1/src/traphandlers.rs:409:44
      wasmtime_runtime::traphandlers::tls::set
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-runtime-8.0.1/src/traphandlers.rs:684:13
      wasmtime_runtime::traphandlers::<impl wasmtime_runtime::traphandlers::call_thread_state::CallThreadState>::with
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-runtime-8.0.1/src/traphandlers.rs:409:19
  31: wasmtime_runtime::traphandlers::catch_traps
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-runtime-8.0.1/src/traphandlers.rs:224:18
      wasmtime::func::invoke_wasm_and_catch_traps
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-8.0.1/src/func.rs:1306:22
  32: wasmtime::func::typed::TypedFunc<Params,Results>::call_raw
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-8.0.1/src/func/typed.rs:177:22
      wasmtime::func::typed::TypedFunc<Params,Results>::call
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-8.0.1/src/func/typed.rs:88:18
  33: sc_executor_wasmtime::instance_wrapper::EntryPoint::call
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-executor-wasmtime-0.28.0/src/instance_wrapper.rs:69:5
  34: sc_executor_wasmtime::runtime::perform_call
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-executor-wasmtime-0.28.0/src/runtime.rs:702:12
      sc_executor_wasmtime::runtime::WasmtimeInstance::call_impl
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-executor-wasmtime-0.28.0/src/runtime.rs:178:5
      <sc_executor_wasmtime::runtime::WasmtimeInstance as sc_executor_common::wasm_runtime::WasmInstance>::call_with_allocation_stats
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-executor-wasmtime-0.28.0/src/runtime.rs:191:16
  35: sc_executor_common::wasm_runtime::WasmInstance::call
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-executor-common-0.28.0/src/wasm_runtime.rs:91:3
      sc_executor_common::wasm_runtime::WasmInstance::call_export
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-executor-common-0.28.0/src/wasm_runtime.rs:111:3
  36: <sc_executor::executor::WasmExecutor<H> as sp_core::traits::CodeExecutor>::call::{{closure}}::{{closure}}
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-executor-0.31.0/src/executor.rs:522:49
      std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
      sc_executor::executor::with_externalities_safe::{{closure}}
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-executor-0.31.0/src/executor.rs:54:3
      environmental::using::{{closure}}
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/environmental-1.1.4/src/lib.rs:124:3
      std::thread::local::LocalKey<T>::try_with
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/thread/local.rs:270:16
      std::thread::local::LocalKey<T>::with
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/thread/local.rs:246:9
      environmental::using
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/environmental-1.1.4/src/lib.rs:115:9
  37: sp_externalities::scope_limited::ext::using
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/environmental-1.1.4/src/lib.rs:295:5
      sp_externalities::scope_limited::set_and_run_with_externalities
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sp-externalities-0.24.0/src/scope_limited.rs:31:2
      sc_executor::executor::with_externalities_safe
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-executor-0.31.0/src/executor.rs:50:2
      <sc_executor::executor::WasmExecutor<H> as sp_core::traits::CodeExecutor>::call::{{closure}}
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-executor-0.31.0/src/executor.rs:522:5
      sc_executor::executor::WasmExecutor<H>::with_instance::{{closure}}
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-executor-0.31.0/src/executor.rs:354:5
      sc_executor::wasm_runtime::VersionedRuntime::with_instance
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-executor-0.31.0/src/wasm_runtime.rs:109:18
      sc_executor::wasm_runtime::RuntimeCache::with_instance
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-executor-0.31.0/src/wasm_runtime.rs:285:6
  38: sc_executor::executor::WasmExecutor<H>::with_instance
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-executor-0.31.0/src/executor.rs:344:9
      <sc_executor::executor::WasmExecutor<H> as sp_core::traits::CodeExecutor>::call
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-executor-0.31.0/src/executor.rs:517:16
      sc_chain_spec::genesis_config_builder::GenesisConfigBuilderRuntimeCaller<EHF>::call
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-chain-spec-26.0.0/src/genesis_config_builder.rs:73:3
  39: sc_chain_spec::genesis_config_builder::GenesisConfigBuilderRuntimeCaller<EHF>::get_storage_for_config
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-chain-spec-26.0.0/src/genesis_config_builder.rs:104:21
  40: sc_chain_spec::genesis_config_builder::GenesisConfigBuilderRuntimeCaller<EHF>::get_storage_for_patch
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-chain-spec-26.0.0/src/genesis_config_builder.rs:136:3
  41: <sc_chain_spec::chain_spec::ChainSpec<G,E,EHF> as sp_runtime::BuildStorage>::assimilate_storage
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-chain-spec-26.0.0/src/chain_spec.rs:175:5
  42: sp_runtime::BuildStorage::build_storage
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sp-runtime-30.0.1/src/lib.rs:218:3
  43: sc_chain_spec::genesis_block::GenesisBlockBuilder<Block,B,E>::new
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-chain-spec-26.0.0/src/genesis_block.rs:113:4
  44: sc_service::builder::new_full_parts_record_import
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-service-0.34.0/src/builder.rs:145:30
      sc_service::builder::new_full_parts
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-service-0.34.0/src/builder.rs:171:2
      staking_miner_playground::service::new_partial
             at node/src/service.rs:82:3
  45: staking_miner_playground::service::new_full
             at node/src/service.rs:160:6
  46: staking_miner_playground::command::run::{{closure}}::{{closure}}
             at node/src/command.rs:107:5
      tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/park.rs:282:63
      tokio::runtime::coop::with_budget
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/coop.rs:107:5
      tokio::runtime::coop::budget
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/coop.rs:73:5
      tokio::runtime::park::CachedParkThread::block_on
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/park.rs:282:31
      tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/context/blocking.rs:66:9
  47: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/multi_thread/mod.rs:87:13
      tokio::runtime::context::runtime::enter_runtime
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/context/runtime.rs:65:16
      tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/multi_thread/mod.rs:86:9
      tokio::runtime::runtime::Runtime::block_on
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/runtime.rs:350:50
  48: sc_cli::runner::Runner<C>::run_node_until_exit
             at /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sc-cli-0.35.0/src/runner.rs:89:26
  49: staking_miner_playground::command::run
             at node/src/command.rs:106:4
  50: staking_miner_playground::main
             at node/src/main.rs:12:2
  51: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:154:18
  52: std::rt::lang_start::{{closure}}
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:167:18
  53: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20
  54: std::rt::lang_start
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:166:17
  55: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  56: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:360:3
  57: _start


Thread 'main' panicked at 'Failed to allocate memory: "Allocator ran out of space"', /home/niklasad1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sp-io-29.0.0/src/lib.rs:1555

This is a bug. Please report it at:

        support.anonymous.an

Error: Service(Client(Storage("wasm call error Execution aborted due to trap: host code panicked while being called by the runtime: Failed to allocate memory: \"Allocator ran out of space\"\nWASM backtrace:\nerror while executing at wasm backtrace:\n    0: 0x1785d5 - <unknown>!sp_io::allocator::extern_host_function_impls::malloc::h1e80e38e14b163d4\n    1: 0x97e99 - <unknown>!alloc::raw_vec::finish_grow::h9d13e309a83d6630\n    2: 0x98985 - <unknown>!alloc::raw_vec::RawVec<T,A>::reserve_for_push::h2bb796ab9f698ad8\n    3: 0x97342 - <unknown>!core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h170609ab14f8547a\n    4: 0x2da08 - <unknown>!alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter::hf4f0f7145f3e15d4\n    5: 0x919c4 - <unknown>!sp_npos_elections::setup_inputs::h198766a4a9e64dd1\n    6: 0xfc426 - <unknown>!sp_npos_elections::phragmen::seq_phragmen::hb19126113acf434b\n    7: 0x14fa82 - <unknown>!frame_election_provider_support::onchain::elect_with_input_bounds::he11a06fb6d2ccb06\n    8: 0x11162c - <unknown>!pallet_staking::pallet::impls::<impl pallet_staking::pallet::pallet::Pallet<T>>::try_trigger_new_era::h684f374e2df14b5c\n    9: 0x1100bf - <unknown>!pallet_staking::pallet::impls::<impl pallet_staking::pallet::pallet::Pallet<T>>::new_session::hdea95a58986a0f23\n   10: 0x110417 - <unknown>!pallet_staking::pallet::impls::<impl pallet_session::SessionManager<<T as frame_system::pallet::Config>::AccountId> for pallet_staking::pallet::pallet::Pallet<T>>::new_session_genesis::h22376a186d5b4339\n   11: 0x157b46 - <unknown>!<runtime::SudoAsStakingSessionManager as pallet_session::SessionManager<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId>>::new_session_genesis::hba9cbb2d284a5780\n   12: 0x108c04 - <unknown>!<pallet_session::pallet::GenesisConfig<T> as frame_support::traits::hooks::BuildGenesisConfig>::build::hbc48c4f7e2d3f239\n   13: 0x15cbee - <unknown>!<runtime::RuntimeGenesisConfig as frame_support::traits::hooks::BuildGenesisConfig>::build::h96973385fff55938\n   14: 0xc62ad - <unknown>!frame_support::genesis_builder_helper::build_config::ha29d0bfeee335b79\n   15: 0xe79ee - <unknown>!GenesisBuilder_build_config")))
```

**Comment by sigurpol** [comment]
Do we want to keep the playground around or should we focus on the zombienet test setup?

**Comment by niklasad1** [comment]
Ignore this, focus only on the multi-block stuff
